### ISSUE TITLE
file extension: *.das or *.iris or ...

### ISSUE THREAD

**Issue by andreas-wuestefeld** [DAS-RCN/RCN_DASformat#8]
Although the data is in fact a HDF5 format, it would be beneficial to indicate data format by a distinctive extension

Does anyone has an opinion on the file extension ".das"?
Is that already being used and causing conflicts?
how about ".iris"?

other suggestions?

**Comment by andreas-wuestefeld** [comment]
format name is now *.miniDAS

**Comment by jpmorten-asn** [comment]
My suggestion would be to avoid confusion by keeping .hdf5 as the extension. To determine the format type/version, the solution is to access the metadata.

**Comment by miili** [comment]
If it is HDF5 I would argue for `.hdf5`.

However it is to argue that our data is not hierarchical whatsoever and we may be better off defining a binary data format ourselves. After all the data is rather simple. HDF5 may be overkill.

**Comment by anowacki** [comment]
I agree that .hdf5 or .h5 (more common in my experience) is better.  Using HDF5 is nice because it is self-describing and can already be ready easily in many environments, so I'm happy with that as a format and don't think we need to devise another binary format.  I agree with @jpmorten-asn that the file metadata should be used to tell that it is miniDAS and which version of the file format it is.
